const CATEGORIES={zombie:['Undead Uplink','Graveyard Glide','Biohazard Boulevard','Rotten Relay','Nightfall Nest'],horror:['Shadow Shift','Whisper Woods','Dread District','Phantom Pursuit','Midnight Mall'],fps:['Neon Ops','Pulse Patrol','Vector Valley','Target Tower','Cyber Siege'],party:['Bumper Bash','Color Crash','Rocket Relay','Dance Dome','Chaos Kitchen'],abyss:['Void Venture','Deep Core','Rift Raiders','Blackstar Bay','Abyssal Arcade']};
const WEAPONS=['Pulse Pistol','Nova SMG','Arc Rifle','Comet Carbine','Prism Shotgun','Byte Bow','Rift Launcher','Vortex Blaster','Solar Repeater','Echo Cannon','Frost Burst','Thunder Coil'];
const LOOT={common:['Bandage Roll','Med Pack','Shield Sip','Light Ammo','Build Alloy'],rare:['Nova SMG','Shield Pack','Med Pack+','Heavy Ammo'],epic:['Arc Rifle','Pulse Grenade','Full Shield','Repair Kit'],legendary:['Rift Launcher','Aegis Core','Mythic Med Kit']};
const COSTUMES=['Starter Scout','Shadow Stalker','Prism Prowler','Volt Vixen','Neon Knight','Glitch Guardian'];
const GUNSKINS=['Pulse Pistol','Chrome Comet','Byte Bloom','Abyss Edge','Admin: Crown Breaker'];
const EMOTES=['Laser Lope','Perfect Pop','Squad Slam','Bolt Bounce','Neon Nudge','Hyper Hype','Star Spin'];
const SONGS=['Night Circuit','Pixel Pulse'];
const PACKS=[['Cyber Starter Pack',500,'Starter Costume + Chrome Comet + 500 Bits'],['Drift Pack',900,'3 Emotes + 2 Rare Loot Drops'],['Void Pack',1500,'Abyss Edge + Lobby Song + 1200 Bits'],['Admin Vault',0,'Admin-only Crown Breaker + Crown Avatar']];
const accountsKey='matrix_breaker_accounts_v2',activeKey='matrix_breaker_active_v2';
const state={match:null,builds:[]};
const $=id=>document.getElementById(id);
const cap=s=>s[0].toUpperCase()+s.slice(1);
function accounts(){return JSON.parse(localStorage.getItem(accountsKey)||'[]')}
function saveAccounts(a){localStorage.setItem(accountsKey,JSON.stringify(a))}
function active(){return JSON.parse(localStorage.getItem(activeKey)||'null')}
function saveActive(p){localStorage.setItem(activeKey,JSON.stringify(p));saveAccounts(accounts().map(x=>x.username===p.username?p:x))}
function newPlayer(username,code,role='player'){return {username,code,role,wins:0,bits:1500,achievements:0,inventory:[],cosmetics:['Starter Scout','Pulse Pistol','Laser Lope'],friends:['Nova','Hexa','Mira'],settings:{sound:true,vivid:true,shadows:true}}}
function makeGames(key){return Array.from({length:50},(_,i)=>({name:`${CATEGORIES[key][i%5]} ${String(i+1).padStart(2,'0')}`,players:50+(i*17)%450,wins:(i*13)%900,difficulty:['Easy','Medium','Hard','Epic'][i%4]}))}
function allGames(){return Object.fromEntries(Object.keys(CATEGORIES).map(k=>[k,makeGames(k)]))}
function fmt(n){return new Intl.NumberFormat().format(n)}
function switchScreen(name){document.querySelectorAll('.screen').forEach(s=>s.classList.add('hidden'));const el=$(name==='battle-royale'?'battleRoyaleScreen':name+'Screen');if(el){el.classList.remove('hidden');el.classList.add('active')}document.querySelectorAll('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.screen===name))}
function renderShell(){const p=active();if(!p){$('authScreen').classList.remove('hidden');$('appShell').classList.add('hidden');return}$('authScreen').classList.add('hidden');$('appShell').classList.remove('hidden');$('profileName').textContent=p.username;$('profileRole').textContent=p.role==='admin'?'ADMIN OPERATOR':'ARENA AGENT';$('profileAvatar').textContent=p.role==='admin'?'★':p.username[0].toUpperCase();$('cyberBitsDisplay').textContent=fmt(p.bits);document.querySelector('.profile-card').classList.toggle('admin',p.role==='admin');$('profileName').classList.toggle('admin',p.role==='admin');$('profileRole').classList.toggle('admin',p.role==='admin');renderHub();renderStats();renderCosmetics();renderShop();renderLeaderboard();renderSettings();switchScreen('hub')}
function renderHub(){const p=active(),games=allGames();$('hubContent').innerHTML=`<div class="hero-panel"><div class="panel"><div class="eyebrow">SEASON 09 // CYBER CITY</div><h1>Battle Royale: Break the Matrix</h1><p class="hero-copy">Drop into a giant neon city, search loot, build cover, and be the last breaker standing. Every match is a fresh simulation.</p><div class="inline-actions"><button class="primary-btn" data-start>Start Battle Royale</button><button class="secondary-btn" data-scroll>Explore Modes</button></div></div><div class="panel"><div class="eyebrow">PLAYER CORE</div><div class="stat-grid"><div class="stat-chip"><span class="stat-label">Wins</span><b class="stat-value">${p.wins}</b></div><div class="stat-chip"><span class="stat-label">Cyber Bits</span><b class="stat-value">${fmt(p.bits)}</b></div><div class="stat-chip"><span class="stat-label">Achievements</span><b class="stat-value">${p.achievements}/1000</b></div></div></div></div><div class="panel"><div class="section-title">Five Worlds // 50 Games Each</div><div class="mode-grid">${Object.keys(CATEGORIES).map(k=>`<div class="mode-card"><span class="mode-badge">${k.toUpperCase()}</span><div class="mode-name">${cap(k)}</div><div class="game-meta"><span>50 games</span><span>200 achievements</span></div><button class="secondary-btn" data-mode="${k}">View games</button></div>`).join('')}</div></div><div class="panel"><div class="section-title">Featured Games</div><div class="game-grid">${Object.entries(games).flatMap(([k,v])=>v.slice(0,2).map(g=>`<div class="game-card"><div class="game-header"><span class="game-name">${g.name}</span><span class="pill">${k}</span></div><div class="game-meta"><span>${g.players} online</span><span>${g.difficulty}</span></div></div>`)).join('')}</div></div>`;$('hubContent').querySelector('[data-start]').onclick=()=>startMatch();$('hubContent').querySelector('[data-scroll]').onclick=()=>$('hubContent').querySelector('.mode-grid').scrollIntoView({behavior:'smooth'});$('hubContent').querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>alert(`${cap(b.dataset.mode)} has 50 games and 200 generated achievements.`))}
function renderStats(){$('statsContent').innerHTML=`<div class="section-title">Career Overview</div><div class="stat-grid"><div class="stat-chip"><span class="stat-label">Total Wins</span><b class="stat-value">${active().wins}</b></div><div class="stat-chip"><span class="stat-label">Matches Played</span><b class="stat-value">${active().wins+3}</b></div><div class="stat-chip"><span class="stat-label">Worlds Explored</span><b class="stat-value">5</b></div></div><div class="panel"><h3>Achievement Matrix</h3><p class="hero-copy">1,000 generated achievements: 200 each for Zombie, Horror, FPS, Party, and Abyss. Win matches to unlock Cyber Bits and trophy progress.</p></div>`}
function renderCosmetics(){$('cosmeticsContent').innerHTML=`<div class="section-title">Locker</div><div class="cosmetics-grid">${[...COSTUMES,...GUNSKINS,...EMOTES,...SONGS].map((x,i)=>`<div class="cosmetic-item"><span class="pill">${i<COSTUMES.length?'COSTUME':i<COSTUMES.length+GUNSKINS.length?'WEAPON':i<COSTUMES.length+GUNSKINS.length+EMOTES.length?'EMOTE':'SONG'}</span><h3>${x}</h3><button class="secondary-btn" data-equip="${x}">Equip</button></div>`).join('')}</div>`;$('cosmeticsContent').querySelectorAll('[data-equip]').forEach(b=>b.onclick=()=>{const p=active();if(!p.inventory.includes(b.dataset.equip))p.inventory.push(b.dataset.equip);saveActive(p);alert(`${b.dataset.equip} equipped.`)})}
function renderShop(){$('shopContent').innerHTML=`<div class="section-title">Shop // Rotating Vault</div><p class="hero-copy">The shop supports 20,000+ deterministic refresh variants. Current refresh: ${1+Math.floor(Date.now()/86400000)%20000}.</p><div class="shop-grid">${[...COSTUMES.slice(1),...GUNSKINS.slice(1),...EMOTES].map((x,i)=>`<div class="shop-item"><span class="pill">${i%3===0?'RARE':'FEATURED'}</span><h3>${x}</h3><p style="color:var(--gold)">${200+i*35} Cyber Bits</p><button class="secondary-btn" data-buy="${x}" data-price="${200+i*35}">Buy</button></div>`).join('')}</div><div class="panel"><h3>Bundles</h3>${PACKS.map(x=>`<div class="pack-row"><span><b>${x[0]}</b><small style="display:block;color:var(--muted)">${x[2]}</small></span><button class="secondary-btn" data-pack="${x[0]}" data-price="${x[1]}">${x[1]?'Buy '+x[1]:'Admin Claim'}</button></div>`).join('')}</div>`;$('shopContent').querySelectorAll('[data-buy]').forEach(b=>b.onclick=()=>buy(b.dataset.buy,+b.dataset.price));$('shopContent').querySelectorAll('[data-pack]').forEach(b=>b.onclick=()=>{if(active().role!=='admin'&&b.dataset.pack==='Admin Vault')return alert('Admin Vault is restricted.');buy(b.dataset.pack,+b.dataset.price)})}
function buy(item,price){const p=active();if(price>p.bits)return alert('Not enough Cyber Bits. Win a match or complete an achievement.');p.bits-=price;p.inventory.push(item);saveActive(p);renderShell();switchScreen('shop');alert(`${item} added to your locker.`)}
function renderLeaderboard(){const rows=accounts().sort((a,b)=>b.wins-a.wins).map((p,i)=>`<tr><td><span class="rank-badge">${i+1}</span></td><td>${p.username} ${p.role==='admin'?'<span class="admin-tag">ADMIN</span>':''}</td><td>${p.wins}</td><td>${fmt(p.bits)}</td></tr>`).join('');$('leaderboardContent').innerHTML=`<div class="section-title">Leaderboard</div><div class="panel"><table class="leaderboard-table"><thead><tr><th>Rank</th><th>Breaker</th><th>Wins</th><th>Cyber Bits</th></tr></thead><tbody>${rows||'<tr><td colspan="4">No breakers yet</td></tr>'}</tbody></table></div>`}
function renderSettings(){const p=active();$('settingsContent').innerHTML=`<div class="section-title">Settings</div>${Object.keys(p.settings).map(k=>`<div class="setting-card"><b>${cap(k)}</b><button class="switch ${p.settings[k]?'on':''}" data-setting="${k}"></button></div>`).join('')}`;$('settingsContent').querySelectorAll('[data-setting]').forEach(b=>b.onclick=()=>{const p=active();p.settings[b.dataset.setting]=!p.settings[b.dataset.setting];saveActive(p);renderSettings()})}
function startMatch(){switchScreen('battle-royale');state.match={players:98,health:100,shield:0,ammo:30,inventory:[],zone:100};drawCity();renderInventory();$('playerCount').textContent=state.match.players;$('ammoCount').textContent=state.match.ammo;$('zoneInfo').textContent='Safe';$('buildBtn').onclick=build;$('attackBtn').onclick=fire;$('healBtn').onclick=heal;$('exitMatchBtn').onclick=()=>{switchScreen('hub');renderShell()}}
function drawCity(){const c=$('mapCanvas'),ctx=c.getContext('2d');function resize(){c.width=innerWidth;c.height=innerHeight;ctx.fillStyle='#112a43';ctx.fillRect(0,0,c.width,c.height);for(let i=0;i<35;i++){const x=Math.random()*c.width,y=Math.random()*c.height,w=40+Math.random()*130,h=30+Math.random()*100;ctx.fillStyle=['#183b59','#1c4960','#24375d','#3a2c63'][i%4];ctx.fillRect(x,y,w,h);ctx.fillStyle='#66e7ff55';for(let wx=x+8;wx<x+w-5;wx+=18)for(let wy=y+8;wy<y+h-5;wy+=18)ctx.fillRect(wx,wy,5,6)}ctx.strokeStyle='#66e7ff22';ctx.lineWidth=3;for(let i=0;i<10;i++){ctx.beginPath();ctx.moveTo(Math.random()*c.width,0);ctx.lineTo(Math.random()*c.width,c.height);ctx.stroke()}}resize();window.onresize=resize;const m=$('minimapCanvas').getContext('2d');m.fillStyle='#102b40';m.fillRect(0,0,200,200);for(let i=0;i<25;i++){m.fillStyle=i%2?'#5a8bff':'#9c70ff';m.fillRect(Math.random()*190,Math.random()*190,Math.random()*20+5,Math.random()*20+5)}}
function loot(){const tiers=['common','common','common','rare','rare','epic','legendary'];const tier=tiers[Math.floor(Math.random()*tiers.length)],item=LOOT[tier][Math.floor(Math.random()*LOOT[tier].length)];return {item,tier}}
function renderInventory(){const slots=state.match.inventory; $('inventoryGrid').innerHTML=Array.from({length:6},(_,i)=>{const x=slots[i];return `<div class="inventory-slot ${x?.tier||''}" title="${x?.item||'Empty'}">${x?icon(x.item):''}</div>`}).join('')}
function icon(x){return /med|bandage|shield|aegis/i.test(x)?'✚':/ammo/i.test(x)?'▣':/rifle|pistol|smg|shotgun|launcher|cannon|bow|blaster/i.test(x)?'⚡':'◆'}
function openChest(){if(state.match.inventory.length>=6)return alert('Inventory full. Use or drop an item first.');const x=loot();state.match.inventory.push(x);renderInventory();alert(`${x.tier.toUpperCase()} loot found: ${x.item}`)}
function build(){state.builds.push(Date.now());const c=$('mapCanvas'),ctx=c.getContext('2d');ctx.fillStyle='#66e7ff99';ctx.strokeStyle='#b6f7ff';ctx.fillRect(innerWidth/2-60,innerHeight/2-60,120,12);ctx.strokeRect(innerWidth/2-60,innerHeight/2-60,120,12);alert('Build piece placed. Keep moving!')}
function fire(){if(state.match.ammo<=0)return alert('Reload at a loot cache.');state.match.ammo--;state.match.players=Math.max(1,state.match.players-(Math.random()>.5?1:0));$('ammoCount').textContent=state.match.ammo;$('playerCount').textContent=state.match.players;if(state.match.players===1)endMatch()}
function heal(){const x=state.match.inventory.findIndex(i=>/med|bandage|shield|aegis/i.test(i.item));if(x<0)return openChest();const item=state.match.inventory.splice(x,1)[0];if(/shield|aegis/i.test(item.item)){state.match.shield=Math.min(100,state.match.shield+50);$('shieldFill').style.width=state.match.shield+'%';$('shieldText').textContent=state.match.shield+'/100'}else{state.match.health=Math.min(100,state.match.health+35);$('healthFill').style.width=state.match.health+'%';$('healthText').textContent=state.match.health+'/100'}renderInventory()}
function endMatch(){const p=active();p.wins++;p.bits+=350;p.achievements++;saveActive(p);alert('Victory Royale! +350 Cyber Bits and a new achievement.');switchScreen('hub');renderShell()}
function login(){const username=$('usernameInput').value.trim(),code=$('codeInput').value.trim();if(!username||!code)return alert('Enter username and code.');let a=accounts(),p=a.find(x=>x.username.toLowerCase()===username.toLowerCase()&&x.code===code);if(!p){p=newPlayer(username,code);a.push(p);saveAccounts(a)}localStorage.setItem(activeKey,JSON.stringify(p));renderShell()}
function adminLogin(){const username=$('usernameInput').value.trim();if($('codeInput').value.trim()!=='156913')return alert('Invalid admin code.');let a=accounts(),p=a.find(x=>x.role==='admin'&&x.username===username);if(!p){p=newPlayer(username,'156913','admin');p.bits=999999;p.inventory=['Admin: Crown Breaker','Admin Crown Avatar','Admin VIP Tag'];a.push(p);saveAccounts(a)}localStorage.setItem(activeKey,JSON.stringify(p));renderShell();alert('Admin privileges unlocked: Crown tag, avatar, weapon skin, VIP vault, and 999,999 Cyber Bits.')}
$('authForm').addEventListener('submit',e=>{e.preventDefault();login()});$('adminTab').addEventListener('click',()=>adminLogin());$('quickCreateBtn').addEventListener('click',()=>{ $('usernameInput').value='Breaker'+Math.floor(Math.random()*9000+1000);$('codeInput').value=String(Math.floor(Math.random()*900000+100000));document.querySelector('[data-mode="create"]').click()});document.querySelectorAll('.auth-tab').forEach(t=>t.onclick=()=>{document.querySelectorAll('.auth-tab').forEach(x=>x.classList.remove('active'));t.classList.add('active');if(t.dataset.mode==='admin')adminLogin()});$('logoutBtn').onclick=()=>{localStorage.removeItem(activeKey);location.reload()};document.querySelectorAll('.nav-item').forEach(b=>b.onclick=()=>switchScreen(b.dataset.screen));['backBtn','backBtn2','backBtn3','backBtn4','backBtn5'].forEach(id=>$(id)?.addEventListener('click',()=>switchScreen('hub')));document.addEventListener('keydown',e=>{if(e.key.toLowerCase()==='e'&&state.match)openChest()});
function loading(){let n=0,t=setInterval(()=>{n+=10;$('loadingFill').style.width=n+'%';$('loadingText').textContent=['Initializing Battle Royale...','Generating Cyber City...','Syncing loot tables...','Equipping starter loadout...','Ready to drop.'][Math.min(4,Math.floor(n/25))];if(n>=100){clearInterval(t);setTimeout(()=>{$('loadingScreen').classList.add('hidden');renderShell()},400)}},100)}
if(!localStorage.getItem(accountsKey))saveAccounts([]);loading();